web:
  image: nginx:alpine
  volumes:
   - ./mysite.template:/etc/nginx/conf.d/mysite.template
  ports:
   - "9090:8080"
  environment:
   - PORT=8080
  command: /bin/sh -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"