FROM nginx:alpine
#VOLUME /var/cache/nginx
#COPY --from=node /app/dist /usr/share/nginx/html
#COPY ./default.conf /etc/nginx/conf.d/default.conf

#CMD envsubst < $(pwd)port.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'
