version: '3'
services:
    nginx:
      image: nginx:alpine
      ports:
        - "8080:8080"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./api_proxy.conf:/etc/nginx/conf.d/api_proxy.conf
      depends_on:
        - service1
        - service2
        - service3

    service1:
      build: './service_a'
      ports:
        - '4001:4000'
      environment:
        - PORT=4000

    service2:
      build: './service_b'
      ports:
        - '4002:4000'
      environment:
        - PORT=4000

    service3:
      build: './service_c'
      ports:
      - '4003:4000'
      environment:
      - PORT=4000
